@baseUrl = http://localhost:3000

### Add a new team
POST {{baseUrl}}/team
Content-Type: application/json

{
"name": "La team des Julien",
"description":"Pour réussir à créer des équipes grâce à une requête POST"
}

### update team 
PATCH {{baseUrl}}/team/1
Content-Type: application/json

{
"name": "Equipe transformé en équipe de rêve"
}

### Add a pokemon to a team
POST {{baseUrl}}/team/1/pokemon/25
Content-Type: application/json

### Add a new team pour tester l'ajout de pokemon 
POST {{baseUrl}}/team
Content-Type: application/json

{
"name": "La team pour tester un ajout de Pokemon",
"description":"Je vais ajouter Pikachu à cette équipe"
}

### Add a pokemon to a new team 
POST {{baseUrl}}/team/5/pokemon/25
Content-Type: application/json


### delete one pokemon from a team ( example pokemon avec  id 25 de la team 5) 
DELETE  {{baseUrl}}/team/5/pokemon/25
Content-Type: application/json

### delete a team ( exemple la team 6 )
DELETE  {{baseUrl}}/team/4
Content-Type: application/json
