services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin_pokedex
      POSTGRES_PASSWORD: pokedex
      POSTGRES_DB: pokedex
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api 
    restart: on-failure
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - PG_URL=postgres://admin_pokedex:pokedex@db:5432/pokedex
      - JWT_SECRET=secret_temporaire
      - NODE_ENV=development
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api
    command: npm run dev -- --host

volumes:
  db_data:
